
version: 2

models:
    - name: GA_Totals_Agg
      description: "GoogleAnalytics Totals"
      columns:
          - name: VISITNUMBER
            description: "The primary key for this table"
            

