
version: 2

models:
    - name: GA_Sessions
      description: "GoogleAnalytics Sessions"
      columns:
          - name: VISITNUMBER
            description: "The primary key for this table"
    - name: GA_Totals_Agg
      description: "GoogleAnalytics Totals"
      columns:
          - name: Date
            description: "The primary key for this table"
    
