
version: 2

models:
    - name: GA_Sessions
      description: '{{doc("data_model")}}'
      columns:
          - name: FULLVISITORID
            description: "The primary key for this table"
    - name: GA_Totals_Agg
      description: '{{doc("data_model")}}'
      columns:
          - name: Date
            description: "The primary key for this table"
            tests:
              - not_null              
    - name: GA_TotalHits_Agg
      description: '{{doc("data_model")}}'
      columns:
          - name: Date
            description: "The primary key for this table"
            tests:
              - not_null  
    
    
